package com.esmp.extraction.model;

import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

/**
 * Relationship properties for a BINDS_TO edge from a Vaadin view {@link ClassNode} to an entity
 * {@link ClassNode}.
 *
 * <p>Captures the Vaadin 7 data binding mechanism used to connect the view to the entity
 * (e.g., {@code BeanFieldGroup}, {@code FieldGroup}).
 */
@RelationshipProperties
public class BindsToRelationship {

  /** Internal relationship ID — generated by Neo4j, not a business key. */
  @Id @GeneratedValue private Long id;

  @TargetNode private ClassNode target;

  /**
   * The Vaadin 7 data binding mechanism used (e.g., {@code "BeanFieldGroup"}, {@code "FieldGroup"}).
   */
  private String bindingMechanism;

  public BindsToRelationship() {}

  public BindsToRelationship(ClassNode target, String bindingMechanism) {
    this.target = target;
    this.bindingMechanism = bindingMechanism;
  }

  public Long getId() {
    return id;
  }

  public ClassNode getTarget() {
    return target;
  }

  public void setTarget(ClassNode target) {
    this.target = target;
  }

  public String getBindingMechanism() {
    return bindingMechanism;
  }

  public void setBindingMechanism(String bindingMechanism) {
    this.bindingMechanism = bindingMechanism;
  }
}
