package com.esmp.extraction.model;

import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

/** Relationship properties for a CALLS edge between two MethodNodes. */
@RelationshipProperties
public class CallsRelationship {

  /** Internal relationship ID — generated by Neo4j, not a business key. */
  @Id @GeneratedValue private Long id;

  @TargetNode private MethodNode target;

  /** FQN method ID of the caller, for denormalized lookup without graph traversal. */
  private String callerMethodId;

  /** Source file path where the call site appears. */
  private String callSiteFile;

  /** Line number of the call site. */
  private int callSiteLine;

  public CallsRelationship() {}

  public CallsRelationship(MethodNode target) {
    this.target = target;
  }

  public Long getId() {
    return id;
  }

  public MethodNode getTarget() {
    return target;
  }

  public void setTarget(MethodNode target) {
    this.target = target;
  }

  public String getCallerMethodId() {
    return callerMethodId;
  }

  public void setCallerMethodId(String callerMethodId) {
    this.callerMethodId = callerMethodId;
  }

  public String getCallSiteFile() {
    return callSiteFile;
  }

  public void setCallSiteFile(String callSiteFile) {
    this.callSiteFile = callSiteFile;
  }

  public int getCallSiteLine() {
    return callSiteLine;
  }

  public void setCallSiteLine(int callSiteLine) {
    this.callSiteLine = callSiteLine;
  }
}
