package com.esmp.extraction.model;

import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

/**
 * Relationship properties for a CONTAINS_COMPONENT edge representing the Vaadin 7 layout hierarchy.
 * The source node is the parent container and the target node is the child component.
 */
@RelationshipProperties
public class ContainsComponentRelationship {

  /** Internal relationship ID — generated by Neo4j. */
  @Id @GeneratedValue private Long id;

  /** The child component class node. */
  @TargetNode private ClassNode child;

  /** FQN of the parent component type (e.g., {@code com.vaadin.ui.VerticalLayout}). */
  private String parentComponentType;

  /** FQN of the child component type (e.g., {@code com.vaadin.ui.Button}). */
  private String childComponentType;

  public ContainsComponentRelationship() {}

  public ContainsComponentRelationship(ClassNode child) {
    this.child = child;
  }

  public Long getId() {
    return id;
  }

  public ClassNode getChild() {
    return child;
  }

  public void setChild(ClassNode child) {
    this.child = child;
  }

  public String getParentComponentType() {
    return parentComponentType;
  }

  public void setParentComponentType(String parentComponentType) {
    this.parentComponentType = parentComponentType;
  }

  public String getChildComponentType() {
    return childComponentType;
  }

  public void setChildComponentType(String childComponentType) {
    this.childComponentType = childComponentType;
  }
}
