package com.esmp.extraction.model;

import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

/**
 * Relationship properties for a DEPENDS_ON edge between two {@link ClassNode}s.
 *
 * <p>Captures how one class depends on another — via field injection, constructor injection, or
 * setter injection. The {@code fieldName} denotes the specific field or parameter involved.
 */
@RelationshipProperties
public class DependsOnRelationship {

  /** Internal relationship ID — generated by Neo4j, not a business key. */
  @Id @GeneratedValue private Long id;

  @TargetNode private ClassNode target;

  /**
   * How the dependency is injected.
   * One of {@code "field"}, {@code "constructor"}, {@code "setter"}.
   */
  private String injectionType;

  /** Name of the field or constructor/setter parameter holding the dependency. */
  private String fieldName;

  public DependsOnRelationship() {}

  public DependsOnRelationship(ClassNode target, String injectionType, String fieldName) {
    this.target = target;
    this.injectionType = injectionType;
    this.fieldName = fieldName;
  }

  public Long getId() {
    return id;
  }

  public ClassNode getTarget() {
    return target;
  }

  public void setTarget(ClassNode target) {
    this.target = target;
  }

  public String getInjectionType() {
    return injectionType;
  }

  public void setInjectionType(String injectionType) {
    this.injectionType = injectionType;
  }

  public String getFieldName() {
    return fieldName;
  }

  public void setFieldName(String fieldName) {
    this.fieldName = fieldName;
  }
}
