package com.esmp.extraction.model;

import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

/**
 * Relationship properties for an IMPLEMENTS edge from a {@link ClassNode} to an interface
 * {@link ClassNode}.
 *
 * <p>The {@code resolutionConfidence} indicates whether the interface type was successfully
 * resolved to a known class in the extracted source set.
 */
@RelationshipProperties
public class ImplementsRelationship {

  /** Internal relationship ID — generated by Neo4j, not a business key. */
  @Id @GeneratedValue private Long id;

  @TargetNode private ClassNode target;

  /**
   * Whether the interface type was resolved during extraction.
   * One of {@code "RESOLVED"} (found in source set) or {@code "UNRESOLVED"} (external interface).
   */
  private String resolutionConfidence;

  public ImplementsRelationship() {}

  public ImplementsRelationship(ClassNode target, String resolutionConfidence) {
    this.target = target;
    this.resolutionConfidence = resolutionConfidence;
  }

  public Long getId() {
    return id;
  }

  public ClassNode getTarget() {
    return target;
  }

  public void setTarget(ClassNode target) {
    this.target = target;
  }

  public String getResolutionConfidence() {
    return resolutionConfidence;
  }

  public void setResolutionConfidence(String resolutionConfidence) {
    this.resolutionConfidence = resolutionConfidence;
  }
}
