package com.esmp.extraction.model;

import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

/**
 * Relationship properties for a MAPS_TO_TABLE edge from a JPA entity {@link ClassNode} to its
 * backing {@link DBTableNode}.
 *
 * <p>Created when a class carries a {@code @Table(name = "...")} annotation, establishing an
 * explicit mapping from the Java class to the relational schema.
 */
@RelationshipProperties
public class MapsToTableRelationship {

  /** Internal relationship ID — generated by Neo4j, not a business key. */
  @Id @GeneratedValue private Long id;

  @TargetNode private DBTableNode target;

  public MapsToTableRelationship() {}

  public MapsToTableRelationship(DBTableNode target) {
    this.target = target;
  }

  public Long getId() {
    return id;
  }

  public DBTableNode getTarget() {
    return target;
  }

  public void setTarget(DBTableNode target) {
    this.target = target;
  }
}
