package com.esmp.extraction.model;

import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

/**
 * Relationship properties for a QUERIES edge from a {@link MethodNode} (repository query method)
 * to a {@link DBTableNode}.
 *
 * <p>The {@code queryType} distinguishes between derived query methods (Spring Data naming
 * convention) and explicit {@code @Query}-annotated methods.
 */
@RelationshipProperties
public class QueriesRelationship {

  /** Internal relationship ID — generated by Neo4j, not a business key. */
  @Id @GeneratedValue private Long id;

  @TargetNode private DBTableNode target;

  /**
   * How the query is defined.
   * One of {@code "derived"} (Spring Data method name convention) or {@code "explicit"}
   * ({@code @Query} annotation with JPQL/SQL).
   */
  private String queryType;

  public QueriesRelationship() {}

  public QueriesRelationship(DBTableNode target, String queryType) {
    this.target = target;
    this.queryType = queryType;
  }

  public Long getId() {
    return id;
  }

  public DBTableNode getTarget() {
    return target;
  }

  public void setTarget(DBTableNode target) {
    this.target = target;
  }

  public String getQueryType() {
    return queryType;
  }

  public void setQueryType(String queryType) {
    this.queryType = queryType;
  }
}
